POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Vicky",
    "username": "dinovicky",
    "gender": "Male",
    "email":  "vjvicky1010@gmail.com",
    "password": "Vicky@123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "dinovicky",
    "password": "Vignesh@123" 
}

###

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNuZWhhdmlraSIsImlhdCI6MTc3MjAwMDk4Nn0.sgPmGl5iG5rKXAGNPeQIoG2YcikSbBANF-egj9tV-24

